[metadata]
name = cosmikai-backend
version = 0.1.0
description = CosmiKai backend API for exoplanet detection
license = MIT
author = CosmiKai Team
python_requires = >=3.9

[options]
packages = find:
python_requires = >=3.9
include_package_data = True
install_requires =
    numpy
    pandas
    torch
    scikit-learn
    astropy
    lightkurve[oktopus]
    batman-package
    fastapi
    pydantic
    uvicorn
    pymongo
